Current errors:
melido@melido-ASUS-TUF-Gaming-A15-FA507NV-FA507NV:~/Documents/Gym-Tracker/gym_tracker$ flutter test
00:02 +0: ... Widget Tests Displays workout and soreness data correctly     test/screens/pre_workout_dashboard_test.dart:62:60: Error: Method not found:
'WarmUp'.
              '/warmup': (_) => const WarmupScreen(warmUp: WarmUp()),
                                                           ^^^^^^
test/screens/pre_workout_dashboard_test.dart:62:39: Error: Couldn't find
constructor 'WarmupScreen'.
              '/warmup': (_) => const WarmupScreen(warmUp: WarmUp()),
                                      ^^^^^^^^^^^^
test/screens/pre_workout_dashboard_test.dart:71:26: Error: Undefined name
'WarmupScreen'.
      expect(find.byType(WarmupScreen), findsOneWidget);
                         ^^^^^^^^^^^^
lib/screens/smart_dashboard_screen.dart:38:21: Error: 'await' can only be
used in 'async' or 'async*' methods.
      _preWorkout = await localStorage.getPreWorkout();
                    ^^^^^
00:02 +0 -1: loading /home/melido/Documents/Gym-Tracker/gym_tracker/test/screens/pre_workout_dashboard_test.dart [E]
  Failed to load "/home/melido/Documents/Gym-Tracker/gym_tracker/test/screens/pre_workout_dashboard_test.dart":
  Compilation failed for testPath=/home/melido/Documents/Gym-Tracker/gym_tracker/test/screens/pre_workout_dashboard_test.dart: test/screens/pre_workout_dashboard_test.dart:62:60: Error: Method not found: 'WarmUp'.
                '/warmup': (_) => const WarmupScreen(warmUp: WarmUp()),
                                                             ^^^^^^
  test/screens/pre_workout_dashboard_test.dart:62:39: Error: Couldn't find constructor 'WarmupScreen'.
                '/warmup': (_) => const WarmupScreen(warmUp: WarmUp()),
                                        ^^^^^^^^^^^^
  test/screens/pre_workout_dashboard_test.dart:71:26: Error: Undefined name 'WarmupScreen'.
        expect(find.byType(WarmupScreen), findsOneWidget);
                           ^^^^^^^^^^^^
  lib/screens/smart_dashboard_screen.dart:38:21: Error: 'await' can only be used in 'async' or 'async*' methods.
        _preWorkout = await localStorage.getPreWorkout();
                      ^^^^^
  .

To run this test again: /home/melido/development/flutter/bin/cache/dart-sdk/bin/dart test /home/melido/Documents/Gym-Tracker/gym_tracker/test/screens/pre_workout_dashboard_test.dart -p vm --plain-name 'loading /home/melido/Documents/Gym-Tracker/gym_tracker/test/screens/pre_workout_dashboard_test.dart'
00:02 +0 -2: loading /home/melido/Documents/Gym-Tracker/gym_tracker/test/screens/history_screen_test.dart [E]
  Error: the Dart compiler exited unexpectedly.
  package:flutter_tools/src/base/common.dart 34:3  throwToolExit
  package:flutter_tools/src/compile.dart 907:11    DefaultResidentCompiler._compile.<fn>
  dart:async/zone.dart 1538:47                     _rootRunUnary
  dart:async/zone.dart 1429:19                     _CustomZone.runUnary
  dart:async/future_impl.dart 951:45               Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 980:13               Future._propagateToListeners
  dart:async/future_impl.dart 865:9                Future._propagateToListeners
  dart:async/future_impl.dart 723:5                Future._completeWithValue
  dart:async/future_impl.dart 807:7                Future._asyncCompleteWithValue.<fn>
  dart:async/zone.dart 1525:13                     _rootRun
  dart:async/zone.dart 1422:19                     _CustomZone.run
  dart:async/zone.dart 1321:7                      _CustomZone.runGuarded
  dart:async/zone.dart 1362:23                     _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 40:21         _microtaskLoop
  dart:async/schedule_microtask.dart 49:5          _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 127:13     _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 194:5      _RawReceivePort._handleMessage

00:03 +6 -2: ... Widget Tests Changing workout type saves preferences       test/screens/smart_dashboard_screen_test.dart:43:25: Error: Couldn't find
constructor 'smart_dashboard_screen'.
            home: const smart_dashboard_screen(),
                        ^^^^^^^^^^^^^^^^^^^^^^
test/screens/smart_dashboard_screen_test.dart:63:25: Error: Couldn't find
constructor 'smart_dashboard_screen'.
            home: const smart_dashboard_screen(),
                        ^^^^^^^^^^^^^^^^^^^^^^
test/screens/smart_dashboard_screen_test.dart:83:25: Error: Couldn't find
constructor 'smart_dashboard_screen'.
            home: const smart_dashboard_screen(),
                        ^^^^^^^^^^^^^^^^^^^^^^
test/screens/smart_dashboard_screen_test.dart:103:25: Error: Couldn't find
constructor 'smart_dashboard_screen'.
            home: const smart_dashboard_screen(),
                        ^^^^^^^^^^^^^^^^^^^^^^
test/screens/smart_dashboard_screen_test.dart:123:25: Error: Couldn't find
constructor 'smart_dashboard_screen'.
            home: const smart_dashboard_screen(),
                        ^^^^^^^^^^^^^^^^^^^^^^
test/screens/smart_dashboard_screen_test.dart:143:25: Error: Couldn't find
constructor 'smart_dashboard_screen'.
            home: const smart_dashboard_screen(),
                        ^^^^^^^^^^^^^^^^^^^^^^
test/screens/smart_dashboard_screen_test.dart:167:25: Error: Couldn't find
constructor 'smart_dashboard_screen'.
            home: const smart_dashboard_screen(),
                        ^^^^^^^^^^^^^^^^^^^^^^
test/screens/smart_dashboard_screen_test.dart:183:24: Error: Undefined name
'mockLocalStorageService'.
        create: (_) => mockLocalStorageService,
                       ^^^^^^^^^^^^^^^^^^^^^^^
test/screens/smart_dashboard_screen_test.dart:185:23: Error: Couldn't find
constructor 'smart_dashboard_screen'.
          home: const smart_dashboard_screen(),
                      ^^^^^^^^^^^^^^^^^^^^^^
test/screens/smart_dashboard_screen_test.dart:187:64: Error: Method not
found: 'WarmUp'.
            '/warmup': (context) => const WarmupScreen(warmUp: WarmUp()),
                                                               ^^^^^^
test/screens/smart_dashboard_screen_test.dart:187:43: Error: Couldn't find
constructor 'WarmupScreen'.
            '/warmup': (context) => const WarmupScreen(warmUp: WarmUp()),
                                          ^^^^^^^^^^^^
test/screens/smart_dashboard_screen_test.dart:197:24: Error: Undefined name
'WarmupScreen'.
    expect(find.byType(WarmupScreen), findsOneWidget);
                       ^^^^^^^^^^^^
lib/screens/smart_dashboard_screen.dart:38:21: Error: 'await' can only be
used in 'async' or 'async*' methods.
      _preWorkout = await localStorage.getPreWorkout();
                    ^^^^^
00:03 +6 -3: loading /home/melido/Documents/Gym-Tracker/gym_tracker/test/screens/smart_dashboard_screen_test.dart [E]
  Failed to load "/home/melido/Documents/Gym-Tracker/gym_tracker/test/screens/smart_dashboard_screen_test.dart":
  Compilation failed for testPath=/home/melido/Documents/Gym-Tracker/gym_tracker/test/screens/smart_dashboard_screen_test.dart: test/screens/smart_dashboard_screen_test.dart:43:25: Error: Couldn't find constructor 'smart_dashboard_screen'.
              home: const smart_dashboard_screen(),
                          ^^^^^^^^^^^^^^^^^^^^^^
  test/screens/smart_dashboard_screen_test.dart:63:25: Error: Couldn't find constructor 'smart_dashboard_screen'.
              home: const smart_dashboard_screen(),
                          ^^^^^^^^^^^^^^^^^^^^^^
  test/screens/smart_dashboard_screen_test.dart:83:25: Error: Couldn't find constructor 'smart_dashboard_screen'.
              home: const smart_dashboard_screen(),
                          ^^^^^^^^^^^^^^^^^^^^^^
  test/screens/smart_dashboard_screen_test.dart:103:25: Error: Couldn't find constructor 'smart_dashboard_screen'.
              home: const smart_dashboard_screen(),
                          ^^^^^^^^^^^^^^^^^^^^^^
  test/screens/smart_dashboard_screen_test.dart:123:25: Error: Couldn't find constructor 'smart_dashboard_screen'.
              home: const smart_dashboard_screen(),
                          ^^^^^^^^^^^^^^^^^^^^^^
  test/screens/smart_dashboard_screen_test.dart:143:25: Error: Couldn't find constructor 'smart_dashboard_screen'.
              home: const smart_dashboard_screen(),
                          ^^^^^^^^^^^^^^^^^^^^^^
  test/screens/smart_dashboard_screen_test.dart:167:25: Error: Couldn't find constructor 'smart_dashboard_screen'.
              home: const smart_dashboard_screen(),
                          ^^^^^^^^^^^^^^^^^^^^^^
  test/screens/smart_dashboard_screen_test.dart:183:24: Error: Undefined name 'mockLocalStorageService'.
          create: (_) => mockLocalStorageService,
                         ^^^^^^^^^^^^^^^^^^^^^^^
  test/screens/smart_dashboard_screen_test.dart:185:23: Error: Couldn't find constructor 'smart_dashboard_screen'.
            home: const smart_dashboard_screen(),
                        ^^^^^^^^^^^^^^^^^^^^^^
  test/screens/smart_dashboard_screen_test.dart:187:64: Error: Method not found: 'WarmUp'.
              '/warmup': (context) => const WarmupScreen(warmUp: WarmUp()),
                                                                 ^^^^^^
  test/screens/smart_dashboard_screen_test.dart:187:43: Error: Couldn't find constructor 'WarmupScreen'.
              '/warmup': (context) => const WarmupScreen(warmUp: WarmUp()),
                                            ^^^^^^^^^^^^
  test/screens/smart_dashboard_screen_test.dart:197:24: Error: Undefined name 'WarmupScreen'.
      expect(find.byType(WarmupScreen), findsOneWidget);
                         ^^^^^^^^^^^^
  lib/screens/smart_dashboard_screen.dart:38:21: Error: 'await' can only be used in 'async' or 'async*' methods.
        _preWorkout = await localStorage.getPreWorkout();
                      ^^^^^
  .

To run this test again: /home/melido/development/flutter/bin/cache/dart-sdk/bin/dart test /home/melido/Documents/Gym-Tracker/gym_tracker/test/screens/smart_dashboard_screen_test.dart -p vm --plain-name 'loading /home/melido/Documents/Gym-Tracker/gym_tracker/test/screens/smart_dashboard_screen_test.dart'
00:05 +6 -3: ... WarmupScreen Tests Displays correct warm-up details        test/services/ai_service_test.dart:37:26: Error: Undefined name
'highRepWorkout'.
        workoutHistory: [highRepWorkout],
                         ^^^^^^^^^^^^^^
00:05 +7 -4: loading /home/melido/Documents/Gym-Tracker/gym_tracker/test/services/ai_service_test.dart [E]
  Failed to load "/home/melido/Documents/Gym-Tracker/gym_tracker/test/services/ai_service_test.dart":
  Compilation failed for testPath=/home/melido/Documents/Gym-Tracker/gym_tracker/test/services/ai_service_test.dart: test/services/ai_service_test.dart:37:26: Error: Undefined name 'highRepWorkout'.
          workoutHistory: [highRepWorkout],
                           ^^^^^^^^^^^^^^
  .

To run this test again: /home/melido/development/flutter/bin/cache/dart-sdk/bin/dart test /home/melido/Documents/Gym-Tracker/gym_tracker/test/services/ai_service_test.dart -p vm --plain-name 'loading /home/melido/Documents/Gym-Tracker/gym_tracker/test/services/ai_service_test.dart'
00:05 +8 -5: /home/melido/Documents/Gym-Tracker/gym_tracker/test/services/local_storage_service_test.dart: LocalStorageService Tests Retrieves soreness data correctly [E]
  Expected: 'abc123'
    Actual: 'Chest Day'
     Which: is different.
            Expected: abc123
              Actual: Chest Day
                      ^
             Differ at offset 0

  package:matcher                                     expect
  package:flutter_test/src/widget_tester.dart 474:18  expect
  test/services/local_storage_service_test.dart 56:7  main.<fn>.<fn>

To run this test again: /home/melido/development/flutter/bin/cache/dart-sdk/bin/dart test /home/melido/Documents/Gym-Tracker/gym_tracker/test/services/local_storage_service_test.dart -p vm --plain-name 'LocalStorageService Tests Retrieves soreness data correctly'
00:05 +8 -6: /home/melido/Documents/Gym-Tracker/gym_tracker/test/services/local_storage_service_test.dart: LocalStorageService Tests Returns default soreness when no data exists [E]
  Expected: 'abc123'
    Actual: 'Chest Day'
     Which: is different.
            Expected: abc123
              Actual: Chest Day
                      ^
             Differ at offset 0

  package:matcher                                     expect
  package:flutter_test/src/widget_tester.dart 474:18  expect
  test/services/local_storage_service_test.dart 65:7  main.<fn>.<fn>

To run this test again: /home/melido/development/flutter/bin/cache/dart-sdk/bin/dart test /home/melido/Documents/Gym-Tracker/gym_tracker/test/services/local_storage_service_test.dart -p vm --plain-name 'LocalStorageService Tests Returns default soreness when no data exists'
00:05 +11 -6: /home/melido/Documents/Gym-Tracker/gym_tracker/test/screens/warmup_screen_test.dart: WarmupScreen Tests Shows default values for empty warm-up
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: exactly one matching candidate
  Actual: _TextWidgetFinder:<Found 0 widgets with text "Warmup Recommendation": []>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
<asynchronous suspension>
<asynchronous suspension>
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///home/melido/Documents/Gym-Tracker/gym_tracker/test/screens/warmup_screen_test.dart line 33
The test description was:
  Shows default values for empty warm-up
════════════════════════════════════════════════════════════════════════════════════════════════════
00:05 +11 -7: /home/melido/Documents/Gym-Tracker/gym_tracker/test/screens/warmup_screen_test.dart: WarmupScreen Tests Shows default values for empty warm-up [E]
  Test failed. See exception logs above.
  The test description was: Shows default values for empty warm-up

To run this test again: /home/melido/development/flutter/bin/cache/dart-sdk/bin/dart test /home/melido/Documents/Gym-Tracker/gym_tracker/test/screens/warmup_screen_test.dart -p vm --plain-name 'WarmupScreen Tests Shows default values for empty warm-up'
00:07 +15 -8: /home/melido/Documents/Gym-Tracker/gym_tracker/test/models/warm_up_test.dart: WarmUp Tests suggestForWorkoutType returns correct suggestion [E]
  Expected: 'Hip Openers'
    Actual: 'Lower Body Dynamic Warmup'
     Which: is different.
            Expected: Hip Opener ...
              Actual: Lower Body ...
                      ^
             Differ at offset 0

  package:matcher                                     expect
  package:flutter_test/src/widget_tester.dart 474:18  expect
  test/models/warm_up_test.dart 27:7                  main.<fn>.<fn>

To run this test again: /home/melido/development/flutter/bin/cache/dart-sdk/bin/dart test /home/melido/Documents/Gym-Tracker/gym_tracker/test/models/warm_up_test.dart -p vm --plain-name 'WarmUp Tests suggestForWorkoutType returns correct suggestion'
00:09 +33 -9: /home/melido/Documents/Gym-Tracker/gym_tracker/test/models_test.dart: Model Tests WarmUp suggestForWorkoutType returns correct suggestion [E]
  Expected: 'Hip Openers'
    Actual: 'Lower Body Dynamic Warmup'
     Which: is different.
            Expected: Hip Opener ...
              Actual: Lower Body ...
                      ^
             Differ at offset 0

  package:matcher                                     expect
  package:flutter_test/src/widget_tester.dart 474:18  expect
  test/models_test.dart 87:7                          main.<fn>.<fn>

To run this test again: /home/melido/development/flutter/bin/cache/dart-sdk/bin/dart test /home/melido/Documents/Gym-Tracker/gym_tracker/test/models_test.dart -p vm --plain-name 'Model Tests WarmUp suggestForWorkoutType returns correct suggestion'
00:09 +35 -9: Some tests failed.
melido@melido-ASUS-TUF-Gaming-A15-FA507NV-FA507NV:~/Documents/Gym-Tracker/gym_tracker$